VP.Reports/Models/ReportDesignerModel.cs
using System.Collections.Generic;
using DevExpress.DataAccess.Sql;

namespace VP.Reports.Models {
    public class ReportDesignerModel {
        public Dictionary<string, object> DataSources { get; set; }
    }
}

VP.Reports/Models/StatusMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VP.Reports.Models
{
    public class StatusMessage
    {
        public string Status { get; set; }
        public string Message { get; set; }
    }
}

VP.Reports/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VP.Reports.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult Designer() {
            Models.ReportDesignerModel model = new Models.ReportDesignerModel();
            return View(model);
        }

        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult Viewer() {
            return View();
        }
    }
}

VP.Reports/Controllers/ReportsController.cs
using DevExpress.XtraReports.Web.WebDocumentViewer.DataContracts;
using System;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VP.Reports.Models;
using VP.Reports.Services;

namespace VP.Reports.Controllers {
    public class ReportsController : Controller {

       private CustomDocumentOperationService _customDocumentOperationService = new CustomDocumentOperationService();

        
        public ReportsController(CustomDocumentOperationService customDocumentOperationService)
        {
            _customDocumentOperationService = customDocumentOperationService;
        }

        public ReportsController()
        {
           
        }
        public ActionResult Index() {
            return View();
        }

        public ActionResult Designer() {
            Models.ReportDesignerModel model = new Models.ReportDesignerModel();
            return View(model);
        }

        public ActionResult Payslip(DateTime? Period) {
            var report = new PaySlip();
            //report.Parameters["Company"].Value = "AppXync";
            //report.Parameters["Branch"].Value = "Lagos";
            return View(report);
        }

        public ActionResult PayAnalysis()
        {
            var report = new PayAnalysis();
            //report.Parameters["Company"].Value = "AppXync";
            //report.Parameters["Branch"].Value = "Lagos";
            return View(report);
        }

        public ActionResult BankSchedule()
        {
            var report = new BankSchedule();
            //report.Parameters["Company"].Value = "AppXync";
            //report.Parameters["Branch"].Value = "Lagos";
            return View(report);
           
        }

        public ActionResult Payee()
        {
            var report = new Payee();
            //report.Parameters["Company"].Value = "AppXync";
            //report.Parameters["Branch"].Value = "Lagos";
            return View(report);
        }

        public ActionResult Pension()
        {
            var report = new Pension();
            //report.Parameters["Company"].Value = "AppXync";
            //report.Parameters["Branch"].Value = "Lagos";
            return View(report);
        }

        public ActionResult PayJournal()
        {
            var report = new PayrollJournal();
            //report.Parameters["Company"].Value = "AppXync";
            //report.Parameters["Branch"].Value = "Lagos";
            return View(report);
        }

        [HttpPost]
        public async Task<ActionResult> EmailPaySlip(StatusMessage sm)
        {   
            
            StatusMessage statusMessage = new StatusMessage();

            statusMessage = _customDocumentOperationService.EmailPaySlip();

            //try
            //{
            //    var companyPolicy = _vpContext.CompanyPolicies.FirstOrDefault();

            //    if (companyPolicy != null)
            //    {
            //        var employees = _vpContext.Employees.ToList();

            //        if (employees != null)
            //        {
            //            foreach (Employee employee in employees)
            //            {
            //                if (employee.EmployeeEmailAddress != null && employee.EmployeeEmailAddress != "")
            //                {
            //                    //load payslip report 
            //                    StaffPaySlip report = new StaffPaySlip();

            //                    string sCurrentPeriod = Convert.ToString(companyPolicy.CurrentPeriod);

            //                    report.Parameters["Period"].Value = Convert.ToDateTime(companyPolicy.CurrentPeriod);
            //                    report.Parameters["EmployeeId"].Value = employee.EmployeeID;

            //                    //export report and send as mail
            //                    var stream = new MemoryStream();
            //                    report.ExportToPdf(stream);
            //                    //return File(stream.GetBuffer(), "application/pdf");

            //                    stream.Position = 0;
            //                    var mailAddress = new MailAddress(employee.EmployeeEmailAddress);
            //                    var recipients = new MailAddressCollection() { mailAddress };
            //                    var attachment = new Attachment(stream, System.Net.Mime.MediaTypeNames.Application.Pdf);
            //                    documentOperationResponse = _customDocumentOperationService.SendEmail(recipients, "Payslip for " + sCurrentPeriod, "Find attached your payslip for " + sCurrentPeriod, attachment);

            //                    if(documentOperationResponse.Succeeded)
            //                    {
            //                        statusMessage.Status = "Success";
            //                        statusMessage.Message = documentOperationResponse.Message;
            //                    }
            //                    else{
            //                        statusMessage.Status = "Failed";
            //                        statusMessage.Message = documentOperationResponse.Message;
            //                    }

            //                }
            //            }
            //        }
            //    }
            //}
            //catch (Exception ex)
            //{
            //    statusMessage.Status = "Failed";
            //    statusMessage.Message = ex.Message;
            //}

            return Json(statusMessage);
        }
    }
}

VP.Reports/Views/Home/Dashboard.cshtml
@*<ul>
    <li/>@Html.ActionLink("Report Designer", "Designer", "Home")
    <li/>@Html.ActionLink("Document Viewer", "Viewer", "Home")
</ul>*@
@{
    //Layout = _Layout;
    ViewData["Title"] = "Dashboard - Vintage Pay Reporting Server";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-sm-12">
                <div class="home-tab">
                    <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Reports</a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#audiences" role="tab" aria-selected="false">Audiences</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="contact-tab" data-bs-toggle="tab" href="#demographics" role="tab" aria-selected="false">Demographics</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link border-0" id="more-tab" data-bs-toggle="tab" href="#more" role="tab" aria-selected="false">More</a>
                                </li>*@
                        </ul>
                        @*<div>
                                <div class="btn-wrapper">
                                    <a href="#" class="btn btn-otline-dark align-items-center"><i class="icon-share"></i> Share</a>
                                    <a href="#" class="btn btn-otline-dark"><i class="icon-printer"></i> Print</a>
                                    <a href="#" class="btn btn-primary text-white me-0"><i class="icon-download"></i> Export</a>
                                </div>
                            </div>*@
                    </div>
                    <div class="tab-content tab-content-basic">
                        <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview">
                            <div class="row">
                                <div class="col-12">
                                    <div class="row">
                                        <div class="col-12 col-sm-6 col-md-6 col-xl-4 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="card-title">
                                                        <a class="nav-link" style="color:#b30718" href="#" onclick="location.href='@Url.Action("../Reports/PaySlip")'">
                                                            Payslip
                                                        </a>
                                                    </h4>
                                                    <div class="d-flex justify-content-between">
                                                        @*<p class="text-muted">@Model.totEmployeeCount</p>
                                                        <p class="text-muted">100%</p>*@
                                                    </div>
                                                    <div class="progress progress-md">
                                                        <div class="progress-bar bg-success w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-6 col-xl-4 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="card-title">
                                                        <a class="nav-link" href="#" style="color:#b30718" onclick="location.href='@Url.Action("../Reports/PayAnalysis")'">
                                                            Pay Analysis
                                                        </a>
                                                    </h4>
                                                   
                                                    <div class="progress progress-md">
                                                        <div class="progress-bar bg-danger w-25" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-6 col-xl-4 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="card-title">
                                                    
                                                        <a class="nav-link" href="#" style="color:#b30718" onclick="location.href='@Url.Action("../Reports/BankSchedule")'">
                                                            Bank Schedule
                                                        </a>
                                                    </h4>
                                                    <div class="d-flex justify-content-between">
                                                        @*<p class="text-muted">@Model.birthdayEmployeeCount</p>
                                                        <p class="text-muted">@Model.birthdayEmployeePer%</p>*@
                                                    </div>
                                                    <div class="progress progress-md">
                                                        <div class="progress-bar bg-info w-25" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-6 col-xl-4 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="card-title">
                                                        <a class="nav-link" href="#" style="color:#b30718" onclick="location.href='@Url.Action("../Reports/PayJournal")'">
                                                            Payroll Journal
                                                        </a>
                                                    </h4>
                                                    <div class="d-flex justify-content-between">
                                                        @*<p class="text-muted">@Model.leaveEmployeeCount</p>
                                                        <p class="text-muted">@Model.leaveEmployeePer%</p>*@
                                                    </div>
                                                    <div class="progress progress-md">
                                                        <div class="progress-bar bg-warning w-25" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-12 col-sm-6 col-md-6 col-xl-4 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="card-title">
                                                         
                                                            <a class="nav-link" href="#" style="color:#b30718" onclick="location.href='@Url.Action("../Reports/Payee")'">
                                                                Tax
                                                            </a>
</h4>
                                                    <div class="d-flex justify-content-between">
                                                        @*<p class="text-muted">@Model.leaveEmployeeCount</p>
                        <p class="text-muted">@Model.leaveEmployeePer%</p>*@
                                                    </div>
                                                    <div class="progress progress-md">
                                                        <div class="progress-bar bg-warning w-25" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-12 col-sm-6 col-md-6 col-xl-4 grid-margin stretch-card">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h4 class="card-title">
                                                        
                                                        <a class="nav-link" href="#" style="color:#b30718" onclick="location.href='@Url.Action("../Reports/Pension")'">
                                                            Pension
                                                        </a>
                                                    </h4>
                                                    <div class="d-flex justify-content-between">
                                                        @*<p class="text-muted">@Model.leaveEmployeeCount</p>
                        <p class="text-muted">@Model.leaveEmployeePer%</p>*@
                                                        
                                                    </div>
                                                    <div class="progress progress-md">
                                                        <div class="progress-bar bg-warning w-25" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

VP.Reports/Views/Home/Designer.cshtml
@Html.DevExpress().ReportDesigner(settings => {
    settings.Name = "ReportDesigner1";
}).Bind(new TestReport()).GetHtml()

VP.Reports/Views/Reports/BankSchedule.cshtml
@{
    //Layout = "_DevExtremeLayout";
    ViewData["Title"] = "Bank Schedule";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-sm-12">
                <div class="home-tab">
                    <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Bank Schedule</a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#audiences" role="tab" aria-selected="false">Audiences</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="contact-tab" data-bs-toggle="tab" href="#demographics" role="tab" aria-selected="false">Demographics</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link border-0" id="more-tab" data-bs-toggle="tab" href="#more" role="tab" aria-selected="false">More</a>
                                </li>*@
                        </ul>
                        <div>
                            @*<div class="btn-wrapper">
                                    <a class="btn btn-danger text-white me-0" asp-action="NewLeave" asp-controller="Transactions"><i class="dx-icon-save"></i> New</a>
                                   <a class="btn btn-success text-white me-0"><i class="dx-icon-download"></i>Import</a>

                                </div>*@
                        </div>
                    </div>
                    <div class="tab-content tab-content-basic">
                        @Html.DevExpress().WebDocumentViewer(settings =>
                                           {
                                               settings.Name = "WebDocumentViewer1";
                                           }).Bind(new BankSchedule()).GetHtml()
                    </div>
                </div>
            </div>
        </div>
    </div>

VP.Reports/Views/Reports/PayAnalysis.cshtml
@{
    //Layout = "_DevExtremeLayout";
    ViewData["Title"] = "Pay Analysis";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-sm-12">
                <div class="home-tab">
                    <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Pay Analysis</a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#audiences" role="tab" aria-selected="false">Audiences</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="contact-tab" data-bs-toggle="tab" href="#demographics" role="tab" aria-selected="false">Demographics</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link border-0" id="more-tab" data-bs-toggle="tab" href="#more" role="tab" aria-selected="false">More</a>
                                </li>*@
                        </ul>
                        <div>
                            @*<div class="btn-wrapper">
                                    <a class="btn btn-danger text-white me-0" asp-action="NewLeave" asp-controller="Transactions"><i class="dx-icon-save"></i> New</a>
                                   <a class="btn btn-success text-white me-0"><i class="dx-icon-download"></i>Import</a>

                                </div>*@
                        </div>
                    </div>
                    <div class="tab-content tab-content-basic">
                        @Html.DevExpress().WebDocumentViewer(settings =>
                                           {
                                               settings.Name = "WebDocumentViewer1";
                                           }).Bind(new PayAnalysis()).GetHtml()
                    </div>
                </div>
            </div>
        </div>
    </div>

VP.Reports/Views/Reports/Payslip.cshtml
@{
    //Layout = "_DevExtremeLayout";
    ViewData["Title"] = "PaySlip";
}
<style>
    .custom-image-item {
        background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB2aWV3Qm94PSIwIDAgMjYgMjYiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDI2IDI2OyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PHN0eWxlIHR5cGU9InRleHQvY3NzIj4uc3Qwe2ZpbGw6IzNEM0QzRDt9PC9zdHlsZT48Zz48cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjUsN2MwLTAuMi0wLjEtMC42LTAuMy0wLjdDMjQuNiw2LjEsMjQuNCw2LDI0LjIsNkgxNnY1LjdsMS45LDEuN0wyNSw3eiIvPjxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0xLDIybDE0LDNWMUwxLDRWMjJ6IE04LDEwYzEuNywwLDMsMS44LDMsNGMwLDIuMi0xLjMsNC0zLDRzLTMtMS44LTMtNEM1LDExLjgsNi4zLDEwLDgsMTB6Ii8+PHBhdGggY2xhc3M9InN0MCIgZD0iTTE4LDE1bC0yLTJsMCw4bDguMiwwYzAuMiwwLDAuNC0wLjEsMC42LTAuM2MwLjItMC4yLDAuMi0wLjQsMC4yLTAuNkwyNSw5TDE4LDE1TDE4LDE1eiIvPjxlbGxpcHNlIGNsYXNzPSJzdDAiIGN4PSI4IiBjeT0iMTQiIHJ4PSIyIiByeT0iMyIvPjwvZz48L3N2Zz4NCg==);
        background-repeat: no-repeat;
    }
</style>
<script>
    function CustomizeMenuActions(s, e) {
        var itemDisabled = ko.observable(true);
        s.Init.AddHandler(function (s) {
            var exportDisabled = s.GetReportPreview().exportDisabled;
            exportDisabled.subscribe(function (newValue) { itemDisabled(newValue); });
            itemDisabled(exportDisabled());
        });
        var sendViaEmailItem = {
            id: 'someCustomId',
            imageClassName: 'custom-image-item',
            text: 'Send via Email',
            visible: true,
            disabled: itemDisabled,
            clickAction: function () {
                s.PerformCustomDocumentOperation('a.leke@powersoft-solutions.org');
            }
        };
        e.Actions.push(sendViaEmailItem);
    }
</script>
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-sm-12">
                <div class="home-tab">
                    <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">PaySlip</a>
                            </li>
                            @*<li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#audiences" role="tab" aria-selected="false">Audiences</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="contact-tab" data-bs-toggle="tab" href="#demographics" role="tab" aria-selected="false">Demographics</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link border-0" id="more-tab" data-bs-toggle="tab" href="#more" role="tab" aria-selected="false">More</a>
                                </li>*@
                        </ul>
                        <div>
                            <div class="btn-wrapper">
                               @* <a class="btn btn-danger text-white me-0" asp-action="NewLeave" asp-controller="Transactions"><i class="dx-icon-save"></i> New</a>*@
                               <a class="btn btn-success text-white me-0" id="btnSendEmail"><i class="dx-icon-download"></i>Email Payslip</a>
                              @*  <button id="loginBtn" class="btn btn-success text-white me-0" type="submit">Login</button>*@
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <p class="toTitle">
                               
                            </p>
                        </div>
                    </div>
                    <div class="tab-content tab-content-basic">
                        @Html.DevExpress().WebDocumentViewer(settings =>
                   {
                       settings.Name = "WebDocumentViewer1";
                       settings.ClientSideEvents.CustomizeMenuActions = "CustomizeMenuActions";
                       
                   }).Bind(new PaySlip()).GetHtml()

                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        rootUrl = '@Url.Content("~")';

        function checkIfNull(value) {
            return (value == "" || value == null || value == undefined) ? true : false;
        }


        $('#btnSendEmail').click(function (e) {
            e.preventDefault()
            

            var appendTo = '';

            var token = '@Html.AntiForgeryToken()';
            var values = JSON.stringify({ "Status": ".", "Message": "."})
            $.ajax({
                type: 'POST',
                dataType: 'json',
                headers: {
                    RequestVerificationToken: $(token).val()
                },
                url: "@Url.Action("EmailPaySlip", "Reports")",
                data: {"Status": ".", "Message": "." },
                beforeSend: function(){
                    disableButtons()
                },
                success: function (result) {
                    if (result) {
                        if ((result.Status == "Success")) {

                            appendTo = `<span class="alert alert-success loginValidation" style="display: flex; margin-top: 20pt"> ${result.Message}. </span>`
                            $('.toTitle').after(appendTo)
                        }
                        else {
                            appendTo = `<span class="alert alert-danger loginValidation" style="display: flex; margin-top: 20pt"> ${result.Message}. </span>`
                            $('.toTitle').after(appendTo)
                        };
                    }
                    else {
                        appendTo = '<span class="alert alert-danger loginValidation" style="display: flex; margin-top: 20pt">There is an issue with logging you in. Try again or contact system administrator</span>'
                        $('.toTitle').after(appendTo)
                    };
                },
                complete:function(data){
                    // Hide image container
                    enableButtons()
                },
                error: function (err) {
                    appendTo = '<span class="alert alert-danger loginValidation" style="display: flex; margin-top: 20pt">There is an issue with logging you in. Try again or contact system administrator</span>'
                    $('.toTitle').after(appendTo)
                }

            })
        })

        function enableButtons() {
            $("#btnSendEmail").removeClass("disabled").html('Email Payslip');
        }

        function disableButtons() {
            $("#btnSendEmail").addClass("disabled").html('Sending Payslip Email... <i class="fa fa-spinner fa-spin"></i>');
        }
    </script>

VP.Reports/Views/Shared/DisplayTemplates/Boolean.cshtml
@model Boolean?
@Html.DevExpress().CheckBoxFor(m => m, s => {
    s.ReadOnly = true;
}).GetHtml()

VP.Reports/Views/Shared/EditorTemplates/Boolean.cshtml
@model Boolean?
@Html.DevExpress().CheckBoxFor(m => m).GetHtml()

VP.Reports/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?
@Html.DevExpress().DateEditFor(m => m).GetHtml()

VP.Reports/Views/Shared/EditorTemplates/Decimal.cshtml
@model Decimal?
@Html.DevExpress().SpinEditFor(m => m).GetHtml()

VP.Reports/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object

@Html.DevExpress().TextBoxFor(m => m).GetHtml()

VP.Reports/Views/Shared/EditorTemplates/MultilineText.cshtml
@model object
@Html.DevExpress().MemoFor(m => m, s => {
    s.Width = 170;
}).GetHtml()

VP.Reports/Views/Shared/EditorTemplates/Password.cshtml
@model object
@Html.DevExpress().TextBoxFor(m => m, s => {
    s.Properties.Password = true;
}).GetHtml()